### ISSUE TITLE
Cache/FileCache.php refers to non-existent class method

### ISSUE THREAD

**Issue by matthewpennell** [eveseat/eseye#13]
In Cache/FileCache.php, a call is made to `getCachePath()`, but the method doesn't exist in that class or anywhere else I can see. It causes any request to error out if it encounters permission problems in the cache directory.

**Comment by leonjza** [comment]
Oh noes! Thanks for the report. Do you want to submit a PR for this easy getter method?
The method can be added [here](https://github.com/eveseat/eseye/blob/master/src/Cache/FileCache.php#L60) with signature `public function getCachePath(): string`, returning `$this->cache_path;` in the function body.

**Comment by matthewpennell** [comment]
Not sure that's going to work - I tried substituting `$this->cache_path` for the method call when I saw the bug, and then got an error that chmod wasn't allowed. Might have been my hosting being strange, I guess.

**Comment by leonjza** [comment]
Yeah so the fact that the method doesn't exist is definitely a bug. The permissions problem on the other hand is something you will have to solve via a shell session ensuring that the user your PHP is running as can write to the cache directory.

**Comment by matthewpennell** [comment]
Yeah, I figured it out - for some reason my site's file owner was set to root while the php process runs as www-data. Fixed that and it's all okay.

About patching the file - you need to decide if you want to abstract returning the cache path to a method, or just keep using the class variable. Since it's only once place, and you've used the class variable in the previous line, I'd say just use that.

**Comment by leonjza** [comment]
Happy with either way really, but agree to use the same method everywhere.

**Comment by matthewpennell** [comment]
Will submit a PR eventually, unless you get round to fixing it yourself first. :)

**Comment by leonjza** [comment]
Fixed in #17
