### ISSUE TITLE
tokengenerator test script errors

### ISSUE THREAD

**Issue by skiedude** [eveseat/eseye#19]
I'm running the vendor/bin/tokengenerator to do some testing and trying to generate a refreshtoken to use. However when being redirected back to the callback URL, the refresh_token and auth_token fields are blank. 

When I debug the curl and its return value they appear to be undefined.

`[Thu Dec 28 04:48:21 2017] PHP Notice:  Trying to get property of non-object in /eseye/vendor/eveseat/eseye/bin/index.php on line 349
[Thu Dec 28 04:48:21 2017] PHP Stack trace:
[Thu Dec 28 04:48:21 2017] PHP   1. {main}() 
/eseye/vendor/eveseat/eseye/bin/index.php:0`

**Comment by leonjza** [comment]
Heya,

I just double checked and am able to successfully generate myself new tokens using the `tokengenerator` utility. What is the output of a `var_dump($result)` call [here](https://github.com/eveseat/eseye/blob/0.0.10/bin/index.php#L346) for you?

**Comment by skiedude** [comment]
`/eseye/vendor/eveseat/eseye/bin/index.php:346:boolean false` ... doesn't seem to helpful

**Comment by leonjza** [comment]
Pity, care to hop onto [Slack](http://seat-docs.readthedocs.io/en/latest/contact/#slack) so we can debug there?

**Comment by leonjza** [comment]
This looks like it had some funnies where the callback URL was modified for use on a remote server. The `tokengenerator` tool is purely meant to help with getting tokens for local testing.
