### ISSUE TITLE
Add a flag indicating if a response was loaded from the cache

### ISSUE THREAD

**Issue by leonjza** [eveseat/eseye#22]
It would be useful to know if an `EsiResponse` object was built from a cached load or from a live call to the ESI endpoint in question.

**Comment by michaelcooke** [comment]
This should probably be closed and included in a new release for Packagist. :)

**Comment by michaelcooke** [comment]
@leonjza Will you please close this issue and make a new release for Packagist?

**Comment by leonjza** [comment]
Ooh thanks for the reminder! Will get to this asap.

**Comment by leonjza** [comment]
Tagged as 0.0.12. Give packagist a few minutes to catch up.
