### ISSUE TITLE
License GPLv2

### ISSUE THREAD

**Issue by CristianIahn** [eveseat/eseye#38]
Hello, I'm sorry I could not find a way to send a direct message.

If I use your API on a website, do I need to make my site source also available? Or since I'm not distributing it is not necessary?

I always have this doubt about GPL2. Can  you clarify my doubt?

Sorry for the inconvenience, and thank you.

**Comment by herpaderpaldent** [comment]
you can contact @leonjza ingame ('qu1ckkk') or join the SeAT Slack to chat with us. See the contact section: https://eveseat.github.io/docs/about/contact/ 

As for GPL2 i think it is rather clear?
<img width="1011" alt="grafik" src="https://user-images.githubusercontent.com/6583519/42867966-5c2f8eaa-8a71-11e8-8cb5-3fcda8ed8299.png">

**Comment by warlof** [comment]
Hello,

in case you're using eseye as a dependency only; you have nothing special to do except quoting its usage and the attached license itself.

in case you're using part of eseye or a modified version of it; you have to publish your source using the same licence.

**Comment by leonjza** [comment]
While not legal advice, I like to use this site for reference. https://tldrlegal.com/license/gnu-general-public-license-v2

Hope that helps.
