### ISSUE TITLE
[Enhancement] Return Exceptions in Eseye variable

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/eseye#4]
Is it possible for one of the parameters of the Eseye variable being invoked to return the HTTP code state whether its 200, 400, or 403 in the variable for when ESI API is down or not functioning correctly?  Basically when testing I have found if I get a HTTP state other than 200 the application breaks.

**Comment by leonjza** [comment]
Failed requests should throw a `Seat\Eseye\Exceptions\RequestFailedException` which you should handle in your application. The error code for the Exception itself will be the HTTP response code (so something like `$e->getCode()`). You can also get the HTTP response code (and message) by getting the `EsiResponse` from the `RequestFailedException` with something like `$e->getEsiResponse()->getErrorCode()`.

Lets look at a small example to handle errors.

```php
<?php

include 'vendor/autoload.php';

$client_id = 'invalid';
$secret_key = 'invalid';
$refresh_token = 'invalid';

$authentication = new \Seat\Eseye\Containers\EsiAuthentication([
    'client_id'     => $client_id,
    'secret'        => $secret_key,
    'refresh_token' => $refresh_token,
]);

$esi = new \Seat\Eseye\Eseye($authentication);

try {

    $contacts = $esi->invoke('get', '/characters/{character_id}/contacts', [
        'character_id' => 1477919642,
    ]);

} catch (\Seat\Eseye\Exceptions\RequestFailedException $e) {

    // The HTTP Response code and message can be retreived
    // from the exception...
    print $e->getCode() . PHP_EOL;
    print $e->getMessage() . PHP_EOL;

    // .. or from the EsiResponse available from the Exception
    print $e->getEsiResponse()->getErrorCode() . PHP_EOL;
    print $e->getEsiResponse()->error() . PHP_EOL;

    // You can also access the *actual* response we got from
    // ESI as a normal array.
    print_r($e->getEsiResponse());
}
```

Does this help?

**Comment by drkthunder02** [comment]
You are amazing.  This helps with what I was having trouble with.  Thanks for another beautiful example, and a beautiful piece of programming.

**Comment by leonjza** [comment]
👍

**Comment by Eingang** [comment]
It might be handy if this were included in the Wiki documentation because it's not obvious to everyone.

**Comment by leonjza** [comment]
Done thanks: https://github.com/eveseat/eseye/wiki/Handling-Exceptions
