### ISSUE TITLE
[Issue] Send a New Mail Endpoint

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/eseye#43]
When trying to use Eseye to send a new mail, I get the following errors:

 Seat\Eseye\Exceptions\RequestFailedException  : invalid array type for 'recipients', 'mail' is required

The Exception trace:

 1   Seat\Eseye\Fetchers\GuzzleFetcher::httpRequest("post", "https://esi.evetech.net/latest/characters/93738489/mail/?datasource=tranquility", ["Bearer [redacted]", "application/json", "application/json", "Eseye/1.1.6/Eseye Default Library"], "{"approved_cost":50000,"body":"Year 2018 Month: 11<br>","recipients":{"recipient_id":90816088,"recipient_type":"character"},"subject":"Test"}")
      /var/www/w4rpservices/vendor/eveseat/eseye/src/Fetchers/GuzzleFetcher.php:102

  2   Seat\Eseye\Fetchers\GuzzleFetcher::call("post", "https://esi.evetech.net/latest/characters/93738489/mail/?datasource=tranquility", ["Year 2018 Month: 11<br>", "Test"])
      /var/www/w4rpservices/vendor/eveseat/eseye/src/Eseye.php:448

I am using the following code to send a new mail, but I can't figure out what I am doing wrong on the library to make it send the required sections the ESI API is looking for.

$esi->setBody([
                    'approved_cost' => 50000,
                    'body' => $body,
                    'recipients' => [
                        'recipient_id' => (int)$info->character_id,
                        'recipient_type' => 'character',
                    ],
                    'subject' => $subject,
                ])->invoke('post', '/characters/{character_id}/mail/', [
                    'character_id'=> 93738489,
                ]);

Any chance you can help me figure out why the error is coming up?

**Comment by warlof** [comment]
Hi,

The `recipients` field is an array of entity part. You should write this instead :

```
'recipients' => [[
'recipient_id' => (int)$info->character_id,
'recipient_type' => 'character',
]],
```

**Comment by drkthunder02** [comment]
Thanks.  Worked like a charm.
