### ISSUE TITLE
Log Files

### ISSUE THREAD

**Issue by robertspektor** [eveseat/eseye#49]
Hi,
is it possible to change/define the directory of the log files? 

My cronjobs running as www-data and this user have to rights. Thats why I'm getting always this php error:

`Notice: There is no existing directory at "logs" and its not buildable: Permission denied in [...]`

thx for help,
robert

**Comment by warlof** [comment]
Sure, you got a perfect sample on the way to do it here https://github.com/eveseat/eveapi/blob/master/src/Helpers/EseyeSetup.php#L42

Basically, retrieve the config container and set the log path using `logfile_location`

**Comment by robertspektor** [comment]
> Sure, you got a perfect sample on the way to do it here https://github.com/eveseat/eveapi/blob/master/src/Helpers/EseyeSetup.php#L42
> 
> Basically, retrieve the config container and set the log path using `logfile_location`

thx warlof

$config = Configuration::getInstance();
$config->setConfiguration(new EsiConfiguration(['logfile_location' => TMP . "/logs"]));

worked!
