### ISSUE TITLE
[Question] Ways to get Public Data w/o Refresh Token

### ISSUE THREAD

**Issue by drkthunder02** [eveseat/eseye#6]
Is there a way to get the public data using the eseye library without having a refresh token?

**Comment by leonjza** [comment]
Indeed. Just instantiate `Eseye()` without an argument.

```php
include 'vendor/autoload.php';

$esi = new \Seat\Eseye\Eseye();

$character_info = $esi->invoke('get', '/characters/{character_id}/', [
    'character_id' => 1477919642,
]);

echo $character_info->name;
```

**Comment by drkthunder02** [comment]
When running the code you listed, I get a server 500 error.

In my composer file I am using dev-master as the branch.

**Comment by leonjza** [comment]
The 500 hints towards a server side issue. :ccp:.
I just tested this in a fresh `Eseye` project and it works great. Anything you have different from the below?

![screen shot 2017-02-07 at 6 19 01 am](https://cloud.githubusercontent.com/assets/1148127/22677699/5e90b772-ecfd-11e6-9450-9692d1b6aba9.png)

**Comment by drkthunder02** [comment]
It's the stream handler again for me not having the correct file attributes on the logger file.  Sorry for the hassle.

**Comment by leonjza** [comment]
👍
