### ISSUE TITLE
Cache retrieval leaves body and page set for next query.  Need to call cleanupRequestData() in invoke on cache good.

### ISSUE THREAD

**Issue by aubreyshomo** [eveseat/eseye#76]
How to reproduce:

Call the following with logging on, after first caching the results from a prior call:

        $response=$esiClient->page(2)->invoke('get', "/characters/{character_id}/skills/", ['character_id'=>$characterId]);
        $response=$esiClient->invoke('get', "/characters/{character_id}/skills/", ['character_id'=>$characterId]);

Note, the second query still has page=2 in the query_params.  (I know the skills endpoint doesn't support page number, I'm just using the query to illustrate the problem.)

Log entry:

  [2021-11-12 16:04:48] local.INFO: [http 304, not modified] get -> https://esi.evetech.net/latest/characters/XXX/skills/?datasource=tranquility&page=2 [t/e: 0.78s/100]
  [2021-11-12 16:04:48] local.DEBUG: Loaded cached response for get -> https://esi.evetech.net/latest/characters/XXX/skills/?datasource=tranquility&page=2 ["0f2e9eebbc34bf4665c3b75ea3fba34e0f938b4b4c77fa7cb1cfb0ba"]
  [2021-11-12 16:04:48] local.DEBUG: Loaded cached response for get -> https://esi.evetech.net/latest/characters/XXX/skills/?datasource=tranquility&page=2 ["0f2e9eebbc34bf4665c3b75ea3fba34e0f938b4b4c77fa7cb1cfb0ba"]

Note that the 304 did not clear the page=2 upon successful etag cache retrieval.  The second query was straight cache for page=2, even though it should have had a different URI and hash, not including page2.

Problem:

In src/Eseye.php, cleanupRequestData() is only called after successful retrieval of data from the server.  Nowhere in the cache logic is it called, even on cache hit.

Suggested fix:

line 281:  $this->cleanupRequestData();

Do you want me to make a pull request for this, or since it's an easy fix do you just want to make it?

**Comment by leonjza** [comment]
If you don't mind making a PR, that would be great!

**Comment by aubreyshomo** [comment]
Sorry for the delay.  This will be my first PR on github and I'm figuring out how to do it.  It should be up shortly.

**Comment by aubreyshomo** [comment]
I have created pull request #77 for this issue, but one of the tests is failing on formatting in places I didn't make changes.  Not sure on that issue.

Would you please let me know if I did something wrong, or my text editor reformatted a bunch of stuff without telling me and I just tried to commit it or something horrible like that.

https://github.com/eveseat/eseye/pull/77

**Comment by leonjza** [comment]
StyleCI rules changed since the last time it ran for this repo. Don't worry I'll fix it.

**Comment by warlof** [comment]
closing since it has been merged
will be available with eseye 2.5.0
