### ISSUE TITLE
Send empty string / null instead of an empty array in GET requests

### ISSUE THREAD

**Issue by sn0opy** [eveseat/eseye#8]
Mentioned this issue a while ago already just realizing it hasn't been fixed yet.

Probably depending on the system, guzzle doesn't like to use an empty array when performing GET requests. Method causing the issue: `GuzzleFetcher\httpRequest`. 

A stack trace for this won't help much, since Guzzle truncates the actual error message internally

**Comment by leonjza** [comment]
Ah awesome! I forgot about this. This is probably the actual problem and will be a better fix than dd1b19fdc77b15c85d2349770893cf5b8ca97054. Thanks @sn0opy.

**Comment by leonjza** [comment]
Fixed in v0.0.9. Thanks again.
