### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by samuelgrant** [eveseat/eseye#9]
Sorry I may have missed it, is there a method to set a user agent over the headers.

**Comment by leonjza** [comment]
Indeed. The library compiles the user agent [here](https://github.com/eveseat/eseye/blob/master/src/Fetchers/GuzzleFetcher.php#L155-L156). This is derived from the `Seat\Eseye\ Configuration` class.

So in short, to set your own user-agent, you need to get the static instance of the `Configuration` class and set the `http_user_agent ` property.

```php
<?php

use Seat\Eseye\Configuration;

$configuration = Configuration::getInstance();
$configuration->http_user_agent = 'Foo Bar Baz';

```

Thereafter normal operations can continue.

```php
<?php

use Seat\Eseye\Configuration;
use Seat\Eseye\Eseye;

// configure a user agent
$configuration = Configuration::getInstance();
$configuration->http_user_agent = 'Foo Bar Baz';

// initialization of eseye. You dont have to pass along the previously
// created `$configuration` variable as the library also resolves it with `getInstance()`.
$esi = new Eseye();

// make a call
$character_info = $esi->invoke('get', '/characters/{character_id}/', [
    'character_id' => 1477919642,
]);

// get data!
echo $character_info->name;
```

**Comment by samuelgrant** [comment]
Thank you, I am still very new to programming, in regards to web I have been able to work with php for about two months, laravel for six weeks and oauth and ESI for about three. For now I had been writing my own code to make API calls through guzzle but I decided it was time to use a library. It looks good.
